name: build

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: gh script A
        uses: actions/github-script@v6
        with:
          script: |
            console.log(process.cwd())

      - name: gh script A
        uses: actions/github-script@v6
        with:
          working-directory: ./tools
          script: |
            console.log(process.cwd())


  # build2:
  #   runs-on: ubuntu-latest
  #   defaults:
  #     run:
  #       working-directory: tools
  #   matrix:
  #     node-version: [18.x]
  #   steps:
  #     - name: Use Node.js ${{ matrix.node-version }}
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: ${{ matrix.node-version }}
  #     - name: Install dependencies
  #       run: npm ci
  #     - name: run script
  #       run: npm start
