name: publish

on:
  push:
    branches:
      - main
    tags: 
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: script
        run: |
          echo "script run"
