name: publish

on:
  push:
    tags: 
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: script
        run: |
          echo ref: {{ github.ref }}
          echo ref_name: {{ github.ref_name }}
