name: publish

on:
  push:
    tags: 
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/github-script@v7
        id: dist-tag
        script: |
          return context.github.ref_name.test/-/ ? "next" : "latest"

      - name: script
        run: |
          echo ref: ${{ github.ref }}
          echo ref_name: ${{ github.ref_name }}
          echo dist: ${{ steps.dist-tags.outputs.result }}
