name: publish

on:
  push:
    tags: 
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/github-script@v7
        id: dist-tag
        with:
          script: |
            console.log(context.ref)
            return /^\d+\.\d+\.\d+-/.test(context.ref) ? "next" : "latest"

      - name: script
        run: |
          echo ref: ${{ github.ref }}
          echo ref_name: ${{ github.ref_name }}
          echo dist: ${{ steps.dist-tags.outputs.result }}
